// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code.xxxxxx.com/micro/proto/snowflake/snowflake.proto

/*
Package snowflake is a generated protocol buffer package.

It is generated from these files:
	code.xxxxxx.com/micro/proto/snowflake/snowflake.proto

It has these top-level messages:
	Request
	Response
*/
package snowflake

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "snowflake.Request")
	proto.RegisterType((*Response)(nil), "snowflake.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Snowflake service

type SnowflakeClient interface {
	Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type snowflakeClient struct {
	c           client.Client
	serviceName string
}

func NewSnowflakeClient(serviceName string, c client.Client) SnowflakeClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "snowflake"
	}
	return &snowflakeClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *snowflakeClient) Create(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Snowflake.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Snowflake service

type SnowflakeHandler interface {
	Create(context.Context, *Request, *Response) error
}

func RegisterSnowflakeHandler(s server.Server, hdlr SnowflakeHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Snowflake{hdlr}, opts...))
}

type Snowflake struct {
	SnowflakeHandler
}

func (h *Snowflake) Create(ctx context.Context, in *Request, out *Response) error {
	return h.SnowflakeHandler.Create(ctx, in, out)
}

func init() {
	proto.RegisterFile("code.xxxxxx.com/micro/proto/snowflake/snowflake.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4d, 0xce, 0x4f, 0x49,
	0xd5, 0x4b, 0x4c, 0x2e, 0x29, 0x49, 0xcc, 0xd7, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xcd, 0x4c, 0x2e,
	0xca, 0xd7, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0xce, 0xcb, 0x2f, 0x4f, 0xcb, 0x49, 0xcc,
	0x4e, 0x45, 0xb0, 0xf4, 0xc0, 0x32, 0x42, 0x9c, 0x70, 0x01, 0x25, 0x4e, 0x2e, 0xf6, 0xa0, 0xd4,
	0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x29, 0x2e, 0x8e, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2,
	0x54, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0xa6, 0xcc,
	0x14, 0x23, 0x07, 0x2e, 0xce, 0x60, 0x98, 0x1e, 0x21, 0x63, 0x2e, 0x36, 0xe7, 0xa2, 0xd4, 0xc4,
	0x92, 0x54, 0x21, 0x21, 0x3d, 0x84, 0xd1, 0x50, 0x63, 0xa4, 0x84, 0x51, 0xc4, 0x20, 0xe6, 0x29,
	0x31, 0x24, 0xb1, 0x81, 0xad, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x10, 0xf5, 0x7d, 0xd2,
	0xb3, 0x00, 0x00, 0x00,
}
