// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code.xxxxxx.com/micro/proto/following/following.proto

/*
Package following is a generated protocol buffer package.

It is generated from these files:
	code.xxxxxx.com/micro/proto/following/following.proto

It has these top-level messages:
	Record
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	DeleteRequest
	DeleteResponse
	ListRequest
	ListResponse
	StatsRequest
	StatsResponse
*/
package following

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId     int64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,3,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,4,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Object     string `protobuf:"bytes,5,opt,name=object" json:"object,omitempty"`
	CreatedAt  string `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Record) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Record) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Record) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *Record) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Record) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Record) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type CreateRequest struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CreateResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadRequest struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId     int64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,3,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,4,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReadRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *ReadRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type ReadResponse struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type DeleteRequest struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId     int64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,3,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,4,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *DeleteRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type DeleteResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListRequest struct {
	Limit      int64  `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset     int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	UserId     int64  `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,4,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,5,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *ListRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type ListResponse struct {
	Total   int32     `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Results []*Record `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetResults() []*Record {
	if m != nil {
		return m.Results
	}
	return nil
}

type StatsRequest struct {
	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,2,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,3,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *StatsRequest) Reset()                    { *m = StatsRequest{} }
func (m *StatsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()               {}
func (*StatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StatsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StatsRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *StatsRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type StatsResponse struct {
	Total int32 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
}

func (m *StatsResponse) Reset()                    { *m = StatsResponse{} }
func (m *StatsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()               {}
func (*StatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StatsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Record)(nil), "following.Record")
	proto.RegisterType((*CreateRequest)(nil), "following.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "following.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "following.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "following.ReadResponse")
	proto.RegisterType((*DeleteRequest)(nil), "following.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "following.DeleteResponse")
	proto.RegisterType((*ListRequest)(nil), "following.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "following.ListResponse")
	proto.RegisterType((*StatsRequest)(nil), "following.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "following.StatsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Following service

type FollowingClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...client.CallOption) (*StatsResponse, error)
}

type followingClient struct {
	c           client.Client
	serviceName string
}

func NewFollowingClient(serviceName string, c client.Client) FollowingClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "following"
	}
	return &followingClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *followingClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Following.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followingClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Following.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followingClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Following.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followingClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Following.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followingClient) Stats(ctx context.Context, in *StatsRequest, opts ...client.CallOption) (*StatsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Following.Stats", in)
	out := new(StatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Following service

type FollowingHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
	Stats(context.Context, *StatsRequest, *StatsResponse) error
}

func RegisterFollowingHandler(s server.Server, hdlr FollowingHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Following{hdlr}, opts...))
}

type Following struct {
	FollowingHandler
}

func (h *Following) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.FollowingHandler.Create(ctx, in, out)
}

func (h *Following) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.FollowingHandler.Read(ctx, in, out)
}

func (h *Following) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.FollowingHandler.Delete(ctx, in, out)
}

func (h *Following) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.FollowingHandler.List(ctx, in, out)
}

func (h *Following) Stats(ctx context.Context, in *StatsRequest, out *StatsResponse) error {
	return h.FollowingHandler.Stats(ctx, in, out)
}

func init() {
	proto.RegisterFile("code.xxxxxx.com/micro/proto/following/following.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x9b, 0x64, 0x93, 0x9a, 0xb3, 0x1f, 0xe0, 0x50, 0xda, 0x71, 0x45, 0x0c, 0x01, 0xa1,
	0x22, 0xec, 0x42, 0xc5, 0x8b, 0x8a, 0x50, 0x44, 0x11, 0x0a, 0xde, 0x18, 0xbd, 0x5f, 0xd2, 0xcc,
	0x59, 0x19, 0xc9, 0x76, 0x62, 0xe6, 0xac, 0xd2, 0xd7, 0xf0, 0x21, 0x7c, 0x0f, 0xdf, 0x4c, 0x76,
	0x26, 0xb3, 0x9b, 0x6c, 0x6b, 0xc0, 0x9b, 0xde, 0xcd, 0xf9, 0x98, 0xfc, 0x7f, 0xe7, 0x63, 0x02,
	0xaf, 0x0a, 0x25, 0x70, 0x96, 0x17, 0x44, 0xb9, 0x9a, 0x15, 0x6a, 0x35, 0x5f, 0xc9, 0xa2, 0x56,
	0xf3, 0xaa, 0x56, 0xa4, 0xe6, 0x4b, 0x55, 0x96, 0xea, 0xa7, 0xbc, 0xfe, 0xba, 0x3b, 0xcd, 0x4c,
	0x84, 0xc5, 0x5b, 0x47, 0xfa, 0xdb, 0x83, 0x28, 0xc3, 0x42, 0xd5, 0x82, 0x4d, 0xc0, 0x97, 0x82,
	0x7b, 0x89, 0x77, 0x1a, 0x64, 0xbe, 0x14, 0xec, 0x04, 0x0e, 0xd7, 0x1a, 0xeb, 0x85, 0x14, 0xdc,
	0x37, 0xce, 0x68, 0x63, 0x5e, 0x0a, 0xf6, 0x14, 0x86, 0xea, 0xea, 0x1b, 0x16, 0xb4, 0xa0, 0x9b,
	0x0a, 0x79, 0x90, 0x78, 0xa7, 0x71, 0x06, 0xd6, 0xf5, 0xe5, 0xa6, 0x42, 0xf6, 0x18, 0xe2, 0x26,
	0x41, 0x0a, 0x3e, 0x30, 0xe1, 0x07, 0xd6, 0x71, 0x29, 0xd8, 0x31, 0x44, 0xf6, 0xcc, 0x43, 0x13,
	0x69, 0x2c, 0xf6, 0x04, 0xa0, 0xa8, 0x31, 0x27, 0x14, 0x8b, 0x9c, 0x78, 0x64, 0x62, 0x71, 0xe3,
	0x79, 0x4b, 0xe9, 0x6b, 0x18, 0xbf, 0x33, 0x46, 0x86, 0xdf, 0xd7, 0xa8, 0x89, 0x3d, 0x87, 0xa8,
	0x36, 0xe0, 0x06, 0x79, 0x78, 0xf6, 0x70, 0xb6, 0x2b, 0xd3, 0x56, 0x94, 0x35, 0x09, 0x69, 0x02,
	0x13, 0x77, 0x57, 0x57, 0xea, 0x5a, 0xe3, 0x7e, 0xad, 0x29, 0xc1, 0x30, 0xc3, 0x5c, 0xb8, 0x6f,
	0xdf, 0x4f, 0x2b, 0xd2, 0x73, 0x18, 0x59, 0xd5, 0x86, 0xea, 0x3f, 0x4a, 0xfa, 0x01, 0xe3, 0xf7,
	0x58, 0xe2, 0xae, 0x1d, 0xf7, 0x84, 0x9c, 0xc0, 0xc4, 0xe9, 0xfe, 0xa3, 0x95, 0xbf, 0x3c, 0x18,
	0x7e, 0x94, 0x9a, 0x1c, 0xd8, 0x11, 0x84, 0xa5, 0x5c, 0x49, 0x6a, 0x52, 0xac, 0x61, 0xb6, 0x60,
	0xb9, 0xd4, 0x48, 0x8e, 0xce, 0x5a, 0x6d, 0xec, 0xa0, 0x0f, 0x7b, 0xd0, 0x8f, 0x1d, 0xee, 0x61,
	0x7f, 0x82, 0x91, 0x65, 0x6a, 0xa0, 0x8f, 0x20, 0x24, 0x45, 0x79, 0x69, 0xa0, 0xc2, 0xcc, 0x1a,
	0xec, 0x05, 0x1c, 0xd6, 0xa8, 0xd7, 0x25, 0x69, 0xee, 0x27, 0xc1, 0xdd, 0x03, 0x70, 0x19, 0x29,
	0xc2, 0xe8, 0x33, 0xe5, 0xa4, 0x5d, 0x9d, 0x2d, 0x72, 0xaf, 0x8f, 0xdc, 0xef, 0x27, 0x0f, 0xf6,
	0xc8, 0x9f, 0xc1, 0xb8, 0x91, 0xe9, 0x43, 0x3f, 0xfb, 0xe3, 0x43, 0xfc, 0xc1, 0xb1, 0xb2, 0x0b,
	0x88, 0xec, 0xc2, 0x33, 0xde, 0xaa, 0xa0, 0xf3, 0x7e, 0xa6, 0x8f, 0xee, 0x88, 0x58, 0x89, 0xf4,
	0x80, 0x9d, 0xc3, 0x60, 0xb3, 0x99, 0xec, 0xb8, 0xd3, 0x80, 0xed, 0x03, 0x99, 0x9e, 0xdc, 0xf2,
	0x6f, 0xaf, 0x5e, 0x40, 0x64, 0x37, 0xa4, 0xa3, 0xdd, 0x59, 0xd6, 0x8e, 0x76, 0x77, 0x9d, 0xac,
	0xf6, 0x66, 0x56, 0x1d, 0xed, 0xd6, 0x42, 0x75, 0xb4, 0xdb, 0x43, 0x4d, 0x0f, 0xd8, 0x1b, 0x08,
	0x4d, 0xb3, 0x58, 0x3b, 0xa7, 0x3d, 0xa5, 0x29, 0xbf, 0x1d, 0x70, 0xb7, 0xaf, 0x22, 0xf3, 0x77,
	0x7c, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xb1, 0x78, 0x00, 0x56, 0x05, 0x00, 0x00,
}
