// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code.xxxxxx.com/micro/proto/favorite/favorite.proto

/*
Package favorite is a generated protocol buffer package.

It is generated from these files:
	code.xxxxxx.com/micro/proto/favorite/favorite.proto

It has these top-level messages:
	Record
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	DeleteRequest
	DeleteResponse
	ListRequest
	ListResponse
	StatsRequest
	StatsResponse
*/
package favorite

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId     int64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,3,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,4,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Object     string `protobuf:"bytes,5,opt,name=object" json:"object,omitempty"`
	CreatedAt  string `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Record) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Record) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Record) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *Record) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *Record) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *Record) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type CreateRequest struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type CreateResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadRequest struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId     int64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,3,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,4,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReadRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *ReadRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type ReadResponse struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type DeleteRequest struct {
	Id         int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId     int64  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,3,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,4,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *DeleteRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type DeleteResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListRequest struct {
	Limit      int64  `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset     int64  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	UserId     int64  `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,4,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,5,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Fields     string `protobuf:"bytes,6,opt,name=fields" json:"fields,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *ListRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *ListRequest) GetFields() string {
	if m != nil {
		return m.Fields
	}
	return ""
}

type ListResponse struct {
	Total   int32     `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Results []*Record `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListResponse) GetResults() []*Record {
	if m != nil {
		return m.Results
	}
	return nil
}

type StatsRequest struct {
	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ObjectType string `protobuf:"bytes,2,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,3,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *StatsRequest) Reset()                    { *m = StatsRequest{} }
func (m *StatsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()               {}
func (*StatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StatsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StatsRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *StatsRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

type StatsResponse struct {
	Total int32 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
}

func (m *StatsResponse) Reset()                    { *m = StatsResponse{} }
func (m *StatsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()               {}
func (*StatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *StatsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Record)(nil), "favorite.Record")
	proto.RegisterType((*CreateRequest)(nil), "favorite.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "favorite.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "favorite.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "favorite.ReadResponse")
	proto.RegisterType((*DeleteRequest)(nil), "favorite.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "favorite.DeleteResponse")
	proto.RegisterType((*ListRequest)(nil), "favorite.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "favorite.ListResponse")
	proto.RegisterType((*StatsRequest)(nil), "favorite.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "favorite.StatsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Favorite service

type FavoriteClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...client.CallOption) (*StatsResponse, error)
}

type favoriteClient struct {
	c           client.Client
	serviceName string
}

func NewFavoriteClient(serviceName string, c client.Client) FavoriteClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "favorite"
	}
	return &favoriteClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *favoriteClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Favorite.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Favorite.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Favorite.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Favorite.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteClient) Stats(ctx context.Context, in *StatsRequest, opts ...client.CallOption) (*StatsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Favorite.Stats", in)
	out := new(StatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Favorite service

type FavoriteHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
	Stats(context.Context, *StatsRequest, *StatsResponse) error
}

func RegisterFavoriteHandler(s server.Server, hdlr FavoriteHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Favorite{hdlr}, opts...))
}

type Favorite struct {
	FavoriteHandler
}

func (h *Favorite) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.FavoriteHandler.Create(ctx, in, out)
}

func (h *Favorite) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.FavoriteHandler.Read(ctx, in, out)
}

func (h *Favorite) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.FavoriteHandler.Delete(ctx, in, out)
}

func (h *Favorite) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.FavoriteHandler.List(ctx, in, out)
}

func (h *Favorite) Stats(ctx context.Context, in *StatsRequest, out *StatsResponse) error {
	return h.FavoriteHandler.Stats(ctx, in, out)
}

func init() {
	proto.RegisterFile("code.xxxxxx.com/micro/proto/favorite/favorite.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x8d, 0x24, 0x4b, 0xb1, 0xc7, 0x1f, 0x94, 0x25, 0x8d, 0x85, 0x4b, 0xa9, 0x10, 0x14, 0x4c,
	0x0f, 0x36, 0x24, 0x87, 0x7e, 0x40, 0x0e, 0xa5, 0xa5, 0x10, 0xe8, 0xa1, 0xa8, 0xbd, 0x1b, 0x45,
	0x3b, 0x86, 0x2d, 0x72, 0xd7, 0xd5, 0x8e, 0x03, 0xf9, 0x43, 0x3d, 0xf4, 0x07, 0xf4, 0xf7, 0x15,
	0xef, 0x87, 0xb3, 0xb6, 0x5b, 0x91, 0x53, 0x6e, 0x7a, 0x33, 0xbb, 0xfb, 0xde, 0xdb, 0x79, 0x2b,
	0xb8, 0xac, 0x24, 0xc7, 0x59, 0x59, 0x11, 0x95, 0x72, 0x56, 0xc9, 0xd5, 0x7c, 0x25, 0xaa, 0x46,
	0xce, 0xd7, 0x8d, 0x24, 0x39, 0x5f, 0x96, 0xb7, 0xb2, 0x11, 0x84, 0xbb, 0x8f, 0x99, 0xae, 0xb3,
	0xae, 0xc3, 0xf9, 0xaf, 0x00, 0x92, 0x02, 0x2b, 0xd9, 0x70, 0x36, 0x82, 0x50, 0xf0, 0x34, 0xc8,
	0x82, 0x69, 0x54, 0x84, 0x82, 0xb3, 0x31, 0x9c, 0x6e, 0x14, 0x36, 0x0b, 0xc1, 0xd3, 0x50, 0x17,
	0x93, 0x2d, 0xbc, 0xe6, 0xec, 0x05, 0xf4, 0xe5, 0xcd, 0x77, 0xac, 0x68, 0x41, 0x77, 0x6b, 0x4c,
	0xa3, 0x2c, 0x98, 0xf6, 0x0a, 0x30, 0xa5, 0x6f, 0x77, 0x6b, 0x64, 0xcf, 0xa0, 0x67, 0x17, 0x08,
	0x9e, 0x76, 0x74, 0xbb, 0x6b, 0x0a, 0xd7, 0x9c, 0x9d, 0x43, 0x62, 0xbe, 0xd3, 0x58, 0x77, 0x2c,
	0x62, 0xcf, 0x01, 0xaa, 0x06, 0x4b, 0x42, 0xbe, 0x28, 0x29, 0x4d, 0x74, 0xaf, 0x67, 0x2b, 0xef,
	0x29, 0x7f, 0x0b, 0xc3, 0x0f, 0x1a, 0x14, 0xf8, 0x73, 0x83, 0x8a, 0xd8, 0x14, 0x92, 0x46, 0x0b,
	0xd7, 0x92, 0xfb, 0x17, 0x4f, 0x66, 0x3b, 0x93, 0xc6, 0x50, 0x61, 0xfb, 0x79, 0x06, 0x23, 0xb7,
	0x55, 0xad, 0xe5, 0x0f, 0x85, 0x87, 0x56, 0x73, 0x82, 0x7e, 0x81, 0x25, 0x77, 0x47, 0x3f, 0xce,
	0x4d, 0xe4, 0x6f, 0x60, 0x60, 0x58, 0xad, 0xaa, 0x87, 0x3b, 0xba, 0x85, 0xe1, 0x47, 0xac, 0xf1,
	0xfe, 0x32, 0x1e, 0x49, 0x71, 0x06, 0x23, 0xc7, 0xfb, 0x9f, 0x9b, 0xfc, 0x1d, 0x40, 0xff, 0xb3,
	0x50, 0xe4, 0x84, 0x9d, 0x41, 0x5c, 0x8b, 0x95, 0x20, 0xbb, 0xc4, 0x00, 0x9d, 0x81, 0xe5, 0x52,
	0x21, 0x39, 0x75, 0x06, 0xf9, 0xb2, 0xa3, 0x36, 0xd9, 0x9d, 0x76, 0xd9, 0xf1, 0x71, 0xe4, 0x96,
	0x02, 0x6b, 0xae, 0x6c, 0xac, 0x2c, 0xca, 0xbf, 0xc0, 0xc0, 0x68, 0xb5, 0x66, 0xce, 0x20, 0x26,
	0x49, 0x65, 0xad, 0xc5, 0xc6, 0x85, 0x01, 0xec, 0x15, 0x9c, 0x36, 0xa8, 0x36, 0x35, 0xa9, 0x34,
	0xcc, 0xa2, 0x7f, 0xce, 0xc5, 0x2d, 0xc8, 0x11, 0x06, 0x5f, 0xa9, 0x24, 0xe5, 0xec, 0x7b, 0x86,
	0x82, 0x36, 0x43, 0x61, 0xbb, 0xa1, 0xe8, 0x60, 0x0e, 0x2f, 0x61, 0x68, 0x69, 0xda, 0x94, 0x5f,
	0xfc, 0x09, 0xa1, 0xfb, 0xc9, 0x4a, 0x65, 0x57, 0x90, 0x98, 0x57, 0xc0, 0xc6, 0xf7, 0xfa, 0xf7,
	0x9e, 0xd4, 0x24, 0x3d, 0x6e, 0x98, 0xf3, 0xf3, 0x13, 0xf6, 0x1a, 0x3a, 0xdb, 0xb0, 0xb2, 0xa7,
	0xbe, 0xf9, 0xdd, 0x93, 0x99, 0x9c, 0x1f, 0x96, 0x77, 0x1b, 0xaf, 0x20, 0x31, 0x99, 0xf1, 0x79,
	0xf7, 0xd2, 0xeb, 0xf3, 0xee, 0xc7, 0xcb, 0xf0, 0x6e, 0x67, 0xe4, 0xf3, 0x7a, 0xf9, 0xf2, 0x79,
	0xfd, 0x51, 0xe6, 0x27, 0xec, 0x1d, 0xc4, 0xfa, 0x8e, 0x98, 0xb7, 0xc4, 0x9f, 0xcd, 0x64, 0x7c,
	0x54, 0x77, 0x7b, 0x6f, 0x12, 0xfd, 0x9b, 0xbc, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x50, 0x00,
	0x2e, 0xc2, 0x5d, 0x05, 0x00, 0x00,
}
