// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code.xxxxxx.com/micro/proto/stats/stats.proto

/*
Package stats is a generated protocol buffer package.

It is generated from these files:
	code.xxxxxx.com/micro/proto/stats/stats.proto

It has these top-level messages:
	UpdateRequest
	UpdateResponse
	Item
	ReadRequest
	ReadResponse
*/
package stats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateRequest struct {
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string `protobuf:"bytes,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Count      int32  `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *UpdateRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Item struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReadRequest struct {
	ObjectType string   `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string   `protobuf:"bytes,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Names      []string `protobuf:"bytes,3,rep,name=names" json:"names,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *ReadRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *ReadRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type ReadResponse struct {
	Id         int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ObjectType string  `protobuf:"bytes,2,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	ObjectId   string  `protobuf:"bytes,3,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Items      []*Item `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReadResponse) GetObjectType() string {
	if m != nil {
		return m.ObjectType
	}
	return ""
}

func (m *ReadResponse) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *ReadResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "stats.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "stats.UpdateResponse")
	proto.RegisterType((*Item)(nil), "stats.Item")
	proto.RegisterType((*ReadRequest)(nil), "stats.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "stats.ReadResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Stats service

type StatsClient interface {
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
}

type statsClient struct {
	c           client.Client
	serviceName string
}

func NewStatsClient(serviceName string, c client.Client) StatsClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "stats"
	}
	return &statsClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *statsClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Stats.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Stats.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Stats service

type StatsHandler interface {
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
}

func RegisterStatsHandler(s server.Server, hdlr StatsHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Stats{hdlr}, opts...))
}

type Stats struct {
	StatsHandler
}

func (h *Stats) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.StatsHandler.Update(ctx, in, out)
}

func (h *Stats) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.StatsHandler.Read(ctx, in, out)
}

func init() { proto.RegisterFile("code.xxxxxx.com/micro/proto/stats/stats.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xc9, 0xbf, 0x8a, 0x5e, 0xa0, 0x42, 0x47, 0x91, 0xa2, 0x32, 0x10, 0x32, 0x65, 0x21,
	0x85, 0x32, 0xf0, 0x19, 0xba, 0x1a, 0x98, 0x91, 0x6b, 0xdf, 0x10, 0xa4, 0xd4, 0xa1, 0xbe, 0x0a,
	0x75, 0xe2, 0xab, 0xa3, 0xd8, 0x29, 0x6a, 0x23, 0xc4, 0xc4, 0x12, 0xe5, 0x7e, 0xbe, 0xbc, 0x77,
	0x79, 0x67, 0xb8, 0x53, 0x46, 0x53, 0x25, 0x15, 0xb3, 0x34, 0x95, 0x32, 0xcd, 0xbc, 0xa9, 0xd5,
	0xc6, 0xcc, 0xdb, 0x8d, 0x61, 0x33, 0xb7, 0x2c, 0xd9, 0xfa, 0x67, 0xe5, 0x08, 0x26, 0xae, 0x28,
	0x3e, 0xe1, 0xfc, 0xb5, 0xd5, 0x92, 0x49, 0xd0, 0xc7, 0x96, 0x2c, 0xe3, 0x0d, 0xa4, 0x66, 0xf5,
	0x4e, 0x8a, 0xdf, 0x78, 0xd7, 0x52, 0x16, 0xe4, 0x41, 0x39, 0x16, 0xe0, 0xd1, 0xcb, 0xae, 0x25,
	0xbc, 0x86, 0x71, 0xdf, 0x50, 0xeb, 0x2c, 0x74, 0xc7, 0xa7, 0x1e, 0x2c, 0x35, 0x22, 0xc4, 0x6b,
	0xd9, 0x50, 0x16, 0x39, 0xee, 0xde, 0x71, 0x0a, 0x89, 0x32, 0xdb, 0x35, 0x67, 0x71, 0x1e, 0x94,
	0x89, 0xf0, 0x45, 0x71, 0x01, 0x93, 0xbd, 0xb1, 0x6d, 0xcd, 0xda, 0x52, 0x71, 0x0f, 0xf1, 0x92,
	0xa9, 0xf9, 0xd1, 0x08, 0x7e, 0xd3, 0x08, 0x0f, 0x35, 0x24, 0xa4, 0x82, 0xa4, 0xfe, 0x9f, 0xd1,
	0xa7, 0x90, 0x74, 0x56, 0x36, 0x8b, 0xf2, 0xa8, 0x1c, 0x0b, 0x5f, 0x14, 0x5f, 0x70, 0xe6, 0x2d,
	0xfc, 0x90, 0x38, 0x81, 0xb0, 0xd6, 0x4e, 0x3a, 0x12, 0x61, 0xad, 0x87, 0x9e, 0xe1, 0xdf, 0x9e,
	0xd1, 0xc0, 0xf3, 0x16, 0x92, 0x9a, 0xa9, 0xb1, 0x59, 0x9c, 0x47, 0x65, 0xba, 0x48, 0x2b, 0xbf,
	0xa1, 0x2e, 0x06, 0xe1, 0x4f, 0x16, 0x16, 0x92, 0xe7, 0x0e, 0xe2, 0x13, 0x8c, 0x7c, 0x60, 0x38,
	0xed, 0xdb, 0x8e, 0x16, 0x37, 0xbb, 0x1a, 0xd0, 0x3e, 0xd5, 0x13, 0x7c, 0x80, 0xb8, 0xfb, 0x05,
	0xc4, 0xbe, 0xe1, 0x20, 0xb2, 0xd9, 0xe5, 0x11, 0xdb, 0x7f, 0xb2, 0x1a, 0xb9, 0x3b, 0xf2, 0xf8,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x13, 0x87, 0x1d, 0x6e, 0x54, 0x02, 0x00, 0x00,
}
